    sources:
      - Lexend.glyphs
    familyName: Lexend
    buildOTF: False
    cleanUp: False
    axisOrder:
      - SPAC
      - wdth
      - wght
    stat:
      - name: Spacing
        tag: SPAC
        values:
        - name: Normal
          value: 100
          flags: 2
        - name: Loose
          value: 150
      - name: Width
        tag: wdth
        values:
        - name: Normal
          value: 100
        - name: SemiExpanded
          value: 112.5
        - name: Expanded
          value: 125
      - name: Weight
        tag: wght
        values:
        - name: Thin
          value: 100
        - name: ExtraLight
          value: 200
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
        - name: ExtraBold
          value: 800